// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1dlD7vryoQRt9DI-swKs-UrWdAKrYMzc',
    appId: '1:153684841188:web:c0e082fad14a9f5c5192f1',
    messagingSenderId: '153684841188',
    projectId: 'pleno-nexo',
    authDomain: 'pleno-nexo.firebaseapp.com',
    storageBucket: 'pleno-nexo.firebasestorage.app',
    measurementId: 'G-GHEQT4SQCY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbVRsVHf_wEUmdcD3kOGaBZSytWPWiNIw',
    appId: '1:153684841188:android:faf888803b7d309f5192f1',
    messagingSenderId: '153684841188',
    projectId: 'pleno-nexo',
    storageBucket: 'pleno-nexo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyCxU4OY4sN-vcxk9ifh59vs22Z__y6sg',
    appId: '1:153684841188:ios:e377d0d6374bf8c65192f1',
    messagingSenderId: '153684841188',
    projectId: 'pleno-nexo',
    storageBucket: 'pleno-nexo.firebasestorage.app',
    iosBundleId: 'com.example.plenonexo',
  );
}
